// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 5/27/2025, 10:39:17 AM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["C:/Users/tsion/Documents/GitHub/jiji-ethiopia-app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/tsion/Documents/GitHub/jiji-ethiopia-app/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/tsion/Documents/GitHub/jiji-ethiopia-app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/tsion/Documents/GitHub/jiji-ethiopia-app/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/tsion/Documents/GitHub/jiji-ethiopia-app/plugins/**/*.{js,ts,mjs}","C:/Users/tsion/Documents/GitHub/jiji-ethiopia-app/composables/**/*.{js,ts,mjs}","C:/Users/tsion/Documents/GitHub/jiji-ethiopia-app/utils/**/*.{js,ts,mjs}","C:/Users/tsion/Documents/GitHub/jiji-ethiopia-app/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/tsion/Documents/GitHub/jiji-ethiopia-app/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/tsion/Documents/GitHub/jiji-ethiopia-app/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/tsion/Documents/GitHub/jiji-ethiopia-app/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;