// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 5/28/2025, 1:30:34 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["C:/Users/tsion/Documents/GitHub/jiji-ethiopia-app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/tsion/Documents/GitHub/jiji-ethiopia-app/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/tsion/Documents/GitHub/jiji-ethiopia-app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/tsion/Documents/GitHub/jiji-ethiopia-app/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/tsion/Documents/GitHub/jiji-ethiopia-app/plugins/**/*.{js,ts,mjs}","C:/Users/tsion/Documents/GitHub/jiji-ethiopia-app/composables/**/*.{js,ts,mjs}","C:/Users/tsion/Documents/GitHub/jiji-ethiopia-app/utils/**/*.{js,ts,mjs}","C:/Users/tsion/Documents/GitHub/jiji-ethiopia-app/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/tsion/Documents/GitHub/jiji-ethiopia-app/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/tsion/Documents/GitHub/jiji-ethiopia-app/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/tsion/Documents/GitHub/jiji-ethiopia-app/app.config.{js,ts,mjs}"]}},
{"darkMode":"class","theme":{"extend":{"colors":{"primary":{"50":"#f0f9ff","100":"#e0f2fe","200":"#bae6fd","300":"#7dd3fc","400":"#38bdf8","500":"#0ea5e9","600":"#0284c7","700":"#0369a1","800":"#075985","900":"#0c4a6e","950":"#082f49"}}}}},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;